[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = "0.31.1"
clap = { version = "4", features = ["derive"] }
solana-client = "2.2.7"
solana-sdk = "2.1.22"
anchor-client = "0.31.1"
anyhow = "1.0"
dirs = "4"
poll_app = { path = "../programs/poll_app" }